// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/ahobsonsayers/twitchets/config"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// PutConfigJSONRequestBody defines body for PutConfig for application/json ContentType.
type PutConfigJSONRequestBody = externalRef0.Config

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Update configuration
	// (PUT /config)
	PutConfig(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get current configuration
// (GET /config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update configuration
// (PUT /config)
func (_ Unimplemented) PutConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutConfig operation middleware
func (siw *ServerInterfaceWrapper) PutConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/config", wrapper.PutConfig)
	})

	return r
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse externalRef0.Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConfig500Response struct {
}

func (response GetConfig500Response) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PutConfigRequestObject struct {
	Body *PutConfigJSONRequestBody
}

type PutConfigResponseObject interface {
	VisitPutConfigResponse(w http.ResponseWriter) error
}

type PutConfig200Response struct {
}

func (response PutConfig200Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutConfig400Response struct {
}

func (response PutConfig400Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutConfig500Response struct {
}

func (response PutConfig500Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// Update configuration
	// (PUT /config)
	PutConfig(ctx context.Context, request PutConfigRequestObject) (PutConfigResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutConfig operation middleware
func (sh *strictHandler) PutConfig(w http.ResponseWriter, r *http.Request) {
	var request PutConfigRequestObject

	var body PutConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutConfig(ctx, request.(PutConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutConfigResponseObject); ok {
		if err := validResponse.VisitPutConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZ63LbuBV+lVNsf9gzunmTdDf8VdlWPJrasmsn4+lEng5EHknYgACDix01o6fpm/TJ",
	"OgBIiqQoR/J621+SwINz+86V+k5imWZSoDCaRN+JjpeYUv81lQly/c8zKeZs4Q4yJTNUhqF/TDP2N1y5",
	"bwnqWLHMMClIRG5Hf/80vh2dR3CHCLej4fnVqJcmMJcKEjSUcQ1SwFI+gZEgZ4YyQTrErDIkEdFGMbEg",
	"HfKtu5BdQVN3OLwZO1HuUKoEFYlO1h0SSyuM8hr8WeGcROSn/saYfm5JvzQjUK87ZMHljHJvA+fXcxJ9",
	"3ovDhb/2kcVf0FwybZhY5L5ZP9T1rVLmJBXd3647REjD5iymwWd7iZ9UrhRyO8R4IR4QZjDVezJrtaIE",
	"gSpFVw0Mqtboqjnv1usOUfjVMoUJiT4XgbEBqGFuCcBG+4dStJz9hrFxujRw24qz/AHEMsHeVJxZpVAY",
	"vgIp+AouToFp0DbLpDKY9KZOLgqbOg0vTisS6xGXH5ontpBG985KE8qnXZY6nj4hqFmSiCyYWdpZL5Zp",
	"ny7lTEuh6QqV7udcyHpjzu4g2jJwJykozBRqhyvE/sQq71rQaByZBrOkBmiW8ZVLMso5BFcDD4z0VFjB",
	"UWvAbxlnMfOOe0SlWJKggNkKKOgMYwdbcbcmqzcVQ7EqJIKQpqDHBJ4Y52A1glkiJDinlpsAQb2GJEz7",
	"INk2/ooJltoUCgo4YiLmNnGy5ojHroQ45lKxBROUQ6ZYjEA1UMhQxSgMXeBUnAfhEThl25gJWR4fBxXn",
	"UqXUkIgk0s44bmqTsOkMVSMvrpg4L6yoRon+wrKu9OZQ3s0kE8Zli1EWG7UAH1GYO5YyThUzLZE+cgTg",
	"5IEuySClJl46C44GvQF04aQ3cAaUBg967+GIci6ftK+9KRNSOS7uTsLmc1QoYtTHhxh9gGmuRKf0W4jf",
	"G4dOC8r0m0c5gJehKkKtiTYTkEkrEg1H//n3cQNWf/tF2NXUG4uYf0B8ganvWip63dBq8QaN6pHFqF1q",
	"Wl0LUs7LLMOkJAy2HVLfq/I+Og/sKO4HGPkXZ6RNP24aTnvGBk+DnOdYaiiag0Mxrz8NBLfuBItzjZ0+",
	"ixfF4BvfmhZMihaFL1AuFM2WLIacxgGikap46TNmo0sNoIKYzetVrzcVHyzn3sQIlsZkOur3f9Qc+jMu",
	"Z/2UMtHnMgDWW8ifLn953718PzgY+Fuv3CvA/fN6vbspX7jwWu2aDI38gi05MMxcpwkp4ElgrmQKgVfr",
	"BFiq0iFW8W2O/5BW5fd9rqCCT7eXz7E6aQ4rjm8n1/iZKaRl+Norx+s9s6UDLoL1+4Fbc7tLR7P31Ymp",
	"XjTIcaFouu+0mJMXDNb7OcoXnuh7OXZ5dTuFyRUttoaxdn4HT7k/rIIVOWZ3PGdU6yepkm3Ib/InvlxQ",
	"a5YojJPna5021PVXOLrOc+2YPDN0HjAwGJmxeFuZ8Rysdh2zKD3O3z297EBKvyBoq9w8xrQbjK1gXy26",
	"ereS9k8vTT6IqSjHvMzOOItLu4GapiLPJ2aHWI0qdOamrE/5k/+dn9/sKhTO9c8Uirz+bm/F/jwsKzAV",
	"N1JrNuMIj5Rb1EAVRlPRhYvTy+sILqVIXLVwv++uI7iT1izzn/f5T7hHbfKzUXE2osXZ1TiCK5ZwKhId",
	"TkbDyD+HoVhwRsPh5DqCiVQF98ko/1nhNLkvzioSzyK4i6Vx7MPJ/TCCe8oxFzYZ55dQCRgrDIS1Fezy",
	"mnSIsy983IePkf+4GvuP0dB/TALJJDyb5JRn/uM+Jxnvu9HlAL3aQne7GS9eoU9v+DZq7lZRipfUjJMd",
	"PdE9hPE5SAULJW1WHLTPVJVM39G6L9CEZv3XU2k+UAerW8AKHQ/quEFEpzDgmVzaa0s+aD925aO51W42",
	"4rMabb4No4bwuqLZyj9KcEIM0FYCV1uZ0cX223F10qf4lEwJHGGamRUEdx0Hvfz3vCA4ws8PBZmPjUDl",
	"tK3QdE/8qbApKhaXD37Por3nYn3ddE/+JqAHpWOMLKyHI1pZv4+9M6B78hr7dmUF84v0c+vzjxrQ627i",
	"Oz20t9WVxPzDNukX4Ohl/D4Qdy7e1WWzsVEf9LK2PjeuHzoHLeSHOqV9bc9dRAVU0hg+PwSP7T+RpK6x",
	"ZC4e55Tr8uxfqOTW3PLLD7b0yX7b+QuiIgDdCIvd3eZtfTU/CNyi527Duu9O/yKIc47/D1i3xtFQ67ab",
	"p6NjYi79Hs4M96/un5iJlw7reocb3rgx6xGVDs476Q16A9d/ZYaCZoxE5E1v0Hvrugk1S49TPy778AJN",
	"25xrFMPHsBLE4Z08bBSotUjiJYXvbpRxY0b5d4lCnUmhQ/v6eTDwM48UJi/xdPMyof+bDgUiRMne/wfl",
	"u+y6GUN3No5R67l1iAclnFPeBR0aO5fDVPjo8a8fUCmp/HiobZpStcqHp8ITdfvXHZLZFid+yhJqggv3",
	"dd2Nrbruq0VtTmWy+iO9tglHF6zrdsia/9lU4896MxPQpcO5n4Dftnv6kXKWbHvwxbjkXm4w9DT+kvbl",
	"qM73UsaUQ4KPyGWWOkQDLcmXZOJW3qjvX+XxpdQm+nXw64CsH9b/DQAA//8OYREEaR0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
