// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package config

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/ahobsonsayers/twigots"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/orsinium-labs/enum"
)

// Defines values for NotificationType.
var (
	notificationTypeBuilder = enum.NewBuilder[string, NotificationType]()

	NotificationTypeGotify   = notificationTypeBuilder.Add(NotificationType{"gotify"})
	NotificationTypeNtfy     = notificationTypeBuilder.Add(NotificationType{"ntfy"})
	NotificationTypeTelegram = notificationTypeBuilder.Add(NotificationType{"telegram"})

	NotificationTypes = notificationTypeBuilder.Enum()
)

// Config defines model for Config.
type Config struct {
	// APIKey REQUIRED: See README.md for details on how to obtain
	APIKey string `json:"apiKey"`

	// Country Country code.
	// Currently only GB is supported.
	Country Country `json:"country"`

	// Notification Notification service configuration
	Notification       NotificationConfig        `json:"notification"`
	GlobalTicketConfig GlobalTicketListingConfig `json:"global"`
	TicketConfigs      []TicketListingConfig     `json:"tickets"`
}

// Country Country code.
// Currently only GB is supported.
type Country = twigots.Country

// GlobalTicketListingConfig GlobalTicketListingConfig represents configuration settings that apply to all ticket listings
// unless explicitly overridden by a specific ticket configuration.
// Any setting not specified will use the default.
type GlobalTicketListingConfig struct {
	// EventSimilarity Event name similarity matching (0.0 - 1.0).
	// Default: 0.9 (allows for minor naming differences)
	EventSimilarity float64 `json:"eventSimilarity,omitempty"`

	// Regions Geographic regions to search for tickets.
	// Default: All regions if not specified.
	// Full list: https://github.com/ahobsonsayers/twigots/blob/main/location.go#L79-L90
	Regions []Region `json:"regions,omitempty"`

	// NumTickets Minimum number of tickets required in listing
	// Default: Any number of tickets.
	NumTickets int `json:"numTickets,omitempty"`

	// MinDiscount Minimum discount (including fee) on the original price as a percentage
	// Default: Any discount (including no discount).
	MinDiscount float64 `json:"discount,omitempty"`

	// MaxTicketPriceInclFee Maximum price per ticket (including fee) in pounds (£)
	// Default: Any price.
	MaxTicketPriceInclFee float64 `json:"maxTicketPrice,omitempty"`

	// Notification Notification services to use
	// Default: All configured services.
	Notification []NotificationType `json:"notification,omitempty"`
}

// GotifyConfig defines model for GotifyConfig.
type GotifyConfig struct {
	// Url Your Gotify server URL
	Url string `json:"url"`

	// Token Application token from Gotify
	Token string `json:"token"`
}

// NotificationConfig Notification service configuration
type NotificationConfig struct {
	Ntfy     *NtfyConfig     `json:"ntfy,omitempty"`
	Gotify   *GotifyConfig   `json:"gotify,omitempty"`
	Telegram *TelegramConfig `json:"telegram,omitempty"`
}

// NotificationType defines model for NotificationType.
type NotificationType enum.Member[string]

// Notifications defines model for Notifications.
type Notifications []NotificationType

// NtfyConfig defines model for NtfyConfig.
type NtfyConfig struct {
	// Url You can use the public instance at https://ntfy.sh
	Url string `json:"url"`

	// Topic If using https://ntfy.sh, make sure this is unique to you!
	Topic string `json:"topic"`

	// Username Username for authenticated instances (Optional)
	Username string `json:"username,omitempty"`

	// Password Password for authenticated instances (Optional)
	Password string `json:"password,omitempty"`
}

// Region Region code.
// Possible values are:
// - GBLO: London
// - GBSO: South
// - GBSW: South West
// - GBSE: South East
// - GBMI: Midlands
// - GBEA: East Anglia
// - GBNO: North
// - GBNE: North East
// - GBNW: North West
// - GBSC: Scotland
// - GBWA: Wales
// - GBNI: Northern Ireland
type Region = twigots.Region

// Regions defines model for Regions.
type Regions []Region

// TelegramConfig defines model for TelegramConfig.
type TelegramConfig struct {
	// Token Get from @BotFather on Telegram
	Token string `json:"token"`

	// ChatId Your chat ID or group chat ID
	ChatId int `json:"chatId"`
}

// TicketListingConfig TicketListingConfig represents configuration for specific ticket listings
// Configuration overrides global configuration
// To reset a global configuration to its default, use:
// - "" (empty string) for string values
// - [] (empty array) for list values
// - -1 for numeric values
type TicketListingConfig struct {
	// Event Event name
	Event string `json:"event"`

	// EventSimilarity Event name similarity matching (0.0 - 1.0).
	// Overrides global setting.
	EventSimilarity *float64 `json:"eventSimilarity,omitempty"`

	// Regions Geographic regions to search for tickets
	// Overrides global setting. To reset to default (all regions), use an empty array [].
	Regions Regions `json:"regions,omitzero"`

	// NumTickets Number of tickets required in listing
	// Overrides global setting. To reset to default (any number), use -1.
	NumTickets *int `json:"numTickets,omitempty"`

	// MinDiscount Minimum discount on the original price as a percentage
	// Overrides global setting. To reset to default (any discount), use -1.
	MinDiscount *float64 `json:"discount,omitempty"`

	// MaxTicketPriceInclFee Maximum price per ticket (including fee) in pounds (£)
	// Overrides global setting. To reset to default (any price), use -1.
	MaxTicketPriceInclFee *float64 `json:"maxTicketPrice,omitempty"`

	// Notification Notification services to use
	// Overrides global setting. To reset to default (all configured services), use an empty array [].
	Notification Notifications `json:"notification,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RY3XLbuhF+lS1OL+wZirKbnJ4Jr+rYikdTW07tZDydyBcQuSLRgAAPANpRM3qavkmf",
	"rAOApEiKsmQnba8ogov9+/ZX30ks80IKFEaT6DvRcYY5dT/PpViy1P4qlCxQGYbunBbsr7iyvxLUsWKF",
	"YVKQiNxO/vZ5eju5iOAOEW4nZxfXkzBPYCkVJGgo4xqkgEw+gZEgF4YyQQJiVgWSiGijmEhJQL6NUjkS",
	"NLeHZx+nVpQ9lCpBRaLTdUBiWQqjnAZ/VLgkEfllvLFiXJkwPq/I1gFJuVxQ7pTn/GZJoi/PX7109J9Y",
	"/BXNFdOGibTyxvqhq2GbsiJpaft2HRAhDVuymHovPS931qKtBQbEOO7O98xgrvdxGdS7cTRViq56fm7r",
	"r9sG/LpeB0Th7yVTmJDoSw3+BoSegY2vN2o/NKLl4h8YG6vL+QbCbhBVHyCWCYZzcV4qhcLwFUjBV3D5",
	"HpgGXRaFVAaTcG4Foihzq9rl+5aobjhVh+aJpdLo8LzRvfk6Yrnl6aKdmoxEJGUmKxdhLPMxzeRCS6Hp",
	"CpUeV1yIdc3uQNmybCcpKCwUagshxO6kVM6ZoNFYMg0mowZoUfCVTR3KOXjnAveM9FyUgqPWgN8KzmLm",
	"PPaISrEkQQGLFVDQBcYWqPpuR1Y4F2diVUsEIU1Njwk8Mc6h1AgmQ0hwSUtuvO+7lSFh2oXFtvHXTLC8",
	"zKGmgCMmYl4mVtYS8dgWBstcKpYyQTkUisUIVAOFAlWMwtAU5+LCC4/AKjvETMjm+NiruJQqp4ZEJJHl",
	"guOm4ogyX6DqZcI1Exe1Fe3w0F9ZMZLOHMpHhWTC2PwwqsRevuMjCnPHcsapYmYgxCeWAKw80A0Z5NTE",
	"mbXg6CQ8gRGchifWgMbgk/AdHFHO5ZN2FTVnQirLxd5J2HKJCkWM+vglRr/ANFt4c/rNx+9Hi84AyvSb",
	"Q9mDV6CqQ62PNhNQyFIkGo7+/a/jHqzu9quw66g3FTH/gPgKU38dqNpdQ9t1GjSqRxajtqlZ6k6Qct5k",
	"GSYNobftoFLeFvTJmr6jjr/Auj9b68r806apDKeqdzHIZQWihroPWPiqwtODbuuON7XS2OqTvir43rgu",
	"lDIpBhS+RJkqWmQshorGIqGRqjhzqbLRpYNMTcyW3XIXzsWHknNnYgSZMYWOxuN97WC84HIxzikTYy49",
	"YGEqf7n67d3o6t3J4YjfOq1+As5/Wq8HGu+lDajVrtHOyK84EO5nhW0qPtodCSyVzMHzGhzhGh0CUiq+",
	"zfHvslTVfZcWqODz7dVzrE77k4jlG1QaD40YA7PUQXnc7YsDXS71Zu/BseNom3Jm/52Zad8wyDFVNN87",
	"7lV09c31Hme4OhJ9b+Ymp1lQm9WSuzVN9RgdPpHuLWOWs9kdlwXV+kmqZBvBj9UXl+i0NBkKYwW5KqUN",
	"tS0Rjm6qZDkmzwyIL+jxRhYs3lZmuoRS2yZXFw3r2lBnAeT0K4IulR2hmLZDbCnY7yXaSrWS5R9em0QQ",
	"U9FMZkW54Cxu7AZq+oo8n2ABKTUq30z7sj5XX/53fn6zK+Gt64cSvqqc23upO/cbBczFR6k1W3CER8pL",
	"1EAVRnMxgsv3VzcRXEmR2Ky373c3EdzJ0mTV6331CveoTXU2qc8mtD67nkZwzRJORaL9yeQsct/hTKSc",
	"UX84u4lgJlXNfTapXlucZvf1WUvieQR3sTSWvT+5P4vgnnKshM2m1SVUAqYKPWFnT7q6IQGx9vnHvX9M",
	"3ON66h6TM/eYeZKZ/zarKM/d474imR66dlUA/fjWdbsZBX6kp64D0qudW4UnzqiZJjv6l/0I0wuQClIl",
	"y6I+GJ54Wtm8o81eovGN9S/vpflALYJ2L6p1fFF39CKC2oChfDloa33RvmprQ3/L3Gyo5x3aajtFDf4P",
	"g37b/STBCjFABwls4WRG19toYIugS+M5mRM4wrwwK/B+OvZ6ud9V0lvCLw81mYsGT2W1bdGMTt2pKHNU",
	"LG4+/Mjie+Cie9N3T7WZh9A4xsjaejiirXX42DkDRqc/Y/9trURusX1und3XXX7uZrzTQwdb3crI/9pm",
	"+wocnYwfA3HnItzeAXsb7mH/jHbnv/VD8KLN+KXeGN6fK99QAa38hS8P3lWHzxm5bR6FDcQl5bo5+ycq",
	"uTWN/LZna54dti2/Ihw8wr142N1f3nZX5cNQrRvqNp6HLtevwrbi+P/Ac2u69NVtu09aOiaW0q3HzHD3",
	"d/kTM3FmQe72tGuZINckII+otPffaXgSnthuKwsUtGAkIm/Ck/CtbSHUZBaj9fo/AQAA///ZVu6thRkA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
